# docker-compose.yml
version: "3.8"

services:
  client:
    build: ./client
    ports:
      - "8080:8080"

  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
    networks:
      default:
        aliases:
          - flask-server

networks:
  default:
